/* tslint:disable */
/* eslint-disable */
/**
 * Product example
 * The cats API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProductDto
 */
export interface CreateProductDto {
    /**
     * 
     * @type {string}
     * @memberof CreateProductDto
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CreateProductDto
     */
    age: number;
    /**
     * 
     * @type {string}
     * @memberof CreateProductDto
     */
    breed: string;
}

/**
 * Check if a given object implements the CreateProductDto interface.
 */
export function instanceOfCreateProductDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "age" in value;
    isInstance = isInstance && "breed" in value;

    return isInstance;
}

export function CreateProductDtoFromJSON(json: any): CreateProductDto {
    return CreateProductDtoFromJSONTyped(json, false);
}

export function CreateProductDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProductDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'age': json['age'],
        'breed': json['breed'],
    };
}

export function CreateProductDtoToJSON(value?: CreateProductDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'age': value.age,
        'breed': value.breed,
    };
}

